### ISSUE TITLE
add this function to checks class

### ISSUE THREAD

**Issue by reut3** [reut3/matala#4]
public static String CheckTimeForWEB(String time1){
		time1=time1.replace('-', '/'); //replact - to /
		String[] FixTime=time1.split(" ");
		String time= "";
		String[] FixDate=FixTime[0].split("/");
		if(FixDate[0].length()==4){
			time+= FixDate[2]+"/"+FixDate[1]+"/"+FixDate[0]+" "+FixTime[1];
			return time;
		}

		else
			time+= FixDate[0]+"/"+FixDate[1]+"/"+FixDate[2]+" "+FixTime[1];
		return time;
	}

**Comment by inon12** [comment]
upload this faction
